
POST http://127.0.0.1:5000/api/usuarios
Content-Type: application/json

{
  "nombre": "Juan Perez",
  "usuario": "jperez",
  "contrasena": "1234"
}

POST http://127.0.0.1:5000/api/login
Content-Type: application/json

{
  "usuario": "jperez",
  "contrasena": "1234"
}

POST http://127.0.0.1:5000/api/login
Content-Type: application/json

{
  "usuario": "jperez",
  "contrasena": "clave_mala"
}


GET http://127.0.0.1:5000/api/expedientes


GET http://127.0.0.1:5000/api/expedientes/1


POST http://127.0.0.1:5000/api/expedientes
Content-Type: application/json

{
  "cliente": "MARIA GONZALEZ",
  "aseguradora_id": 1,
  "juzgado_id": 4,
  "estado": "pendiente",
  "fecha_audiencia": "2019-01-08"
}


PUT http://127.0.0.1:5000/api/expedientes/1
Content-Type: application/json

{
  "estado": "cerrado"
}

DELETE http://127.0.0.1:5000/api/expedientes/7

GET http://127.0.0.1:5000/api/dashboard

GET http://127.0.0.1:5000/api/aseguradoras


GET http://127.0.0.1:5000/api/juzgados
